# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kv.proto',
  package='kv',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x08kv.proto\x12\x02kv\"p\n\x0bRaftRequest\x12\"\n\x04type\x18\x01 \x02(\x0e\x32\x14.kv.RaftRequest.Type\x12\x1e\n\x07request\x18\x02 \x01(\x0b\x32\r.kv.KVRequest\"\x1d\n\x04Type\x12\t\n\x05\x43RASH\x10\x00\x12\n\n\x06KV_REQ\x10\x01\"F\n\tKVRequest\x12\x10\n\x08serialNo\x18\x01 \x02(\x05\x12\x1a\n\x06\x61\x63tion\x18\x02 \x02(\x0e\x32\n.kv.Action\x12\x0b\n\x03\x63md\x18\x03 \x01(\t\"\xb8\x02\n\x0cRaftResponse\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.kv.RaftResponse.Type\x12+\n\x08redirect\x18\x02 \x01(\x0b\x32\x19.kv.RaftResponse.Redirect\x12\'\n\x06result\x18\x03 \x01(\x0b\x32\x17.kv.RaftResponse.Result\x1a\x44\n\x08Redirect\x12&\n\x0foriginalRequest\x18\x01 \x02(\x0b\x32\r.kv.KVRequest\x12\x10\n\x08leaderId\x18\x02 \x02(\x05\x1a\x45\n\x06Result\x12\x10\n\x08serialNo\x18\x01 \x02(\x05\x12\x1a\n\x06\x61\x63tion\x18\x02 \x02(\x0e\x32\n.kv.Action\x12\r\n\x05state\x18\x03 \x03(\t\" \n\x04Type\x12\x0c\n\x08REDIRECT\x10\x00\x12\n\n\x06KV_RES\x10\x01*\x1a\n\x06\x41\x63tion\x12\x07\n\x03GET\x10\x00\x12\x07\n\x03PUT\x10\x01')
)

_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='kv.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=517,
  serialized_end=543,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
GET = 0
PUT = 1


_RAFTREQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='kv.RaftRequest.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CRASH', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KV_REQ', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=99,
  serialized_end=128,
)
_sym_db.RegisterEnumDescriptor(_RAFTREQUEST_TYPE)

_RAFTRESPONSE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='kv.RaftResponse.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REDIRECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KV_RES', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=483,
  serialized_end=515,
)
_sym_db.RegisterEnumDescriptor(_RAFTRESPONSE_TYPE)


_RAFTREQUEST = _descriptor.Descriptor(
  name='RaftRequest',
  full_name='kv.RaftRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='kv.RaftRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='kv.RaftRequest.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RAFTREQUEST_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=128,
)


_KVREQUEST = _descriptor.Descriptor(
  name='KVRequest',
  full_name='kv.KVRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialNo', full_name='kv.KVRequest.serialNo', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='kv.KVRequest.action', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='kv.KVRequest.cmd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=200,
)


_RAFTRESPONSE_REDIRECT = _descriptor.Descriptor(
  name='Redirect',
  full_name='kv.RaftResponse.Redirect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='originalRequest', full_name='kv.RaftResponse.Redirect.originalRequest', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leaderId', full_name='kv.RaftResponse.Redirect.leaderId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=410,
)

_RAFTRESPONSE_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='kv.RaftResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialNo', full_name='kv.RaftResponse.Result.serialNo', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='kv.RaftResponse.Result.action', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='kv.RaftResponse.Result.state', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=481,
)

_RAFTRESPONSE = _descriptor.Descriptor(
  name='RaftResponse',
  full_name='kv.RaftResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='kv.RaftResponse.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='redirect', full_name='kv.RaftResponse.redirect', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='kv.RaftResponse.result', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RAFTRESPONSE_REDIRECT, _RAFTRESPONSE_RESULT, ],
  enum_types=[
    _RAFTRESPONSE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=515,
)

_RAFTREQUEST.fields_by_name['type'].enum_type = _RAFTREQUEST_TYPE
_RAFTREQUEST.fields_by_name['request'].message_type = _KVREQUEST
_RAFTREQUEST_TYPE.containing_type = _RAFTREQUEST
_KVREQUEST.fields_by_name['action'].enum_type = _ACTION
_RAFTRESPONSE_REDIRECT.fields_by_name['originalRequest'].message_type = _KVREQUEST
_RAFTRESPONSE_REDIRECT.containing_type = _RAFTRESPONSE
_RAFTRESPONSE_RESULT.fields_by_name['action'].enum_type = _ACTION
_RAFTRESPONSE_RESULT.containing_type = _RAFTRESPONSE
_RAFTRESPONSE.fields_by_name['type'].enum_type = _RAFTRESPONSE_TYPE
_RAFTRESPONSE.fields_by_name['redirect'].message_type = _RAFTRESPONSE_REDIRECT
_RAFTRESPONSE.fields_by_name['result'].message_type = _RAFTRESPONSE_RESULT
_RAFTRESPONSE_TYPE.containing_type = _RAFTRESPONSE
DESCRIPTOR.message_types_by_name['RaftRequest'] = _RAFTREQUEST
DESCRIPTOR.message_types_by_name['KVRequest'] = _KVREQUEST
DESCRIPTOR.message_types_by_name['RaftResponse'] = _RAFTRESPONSE
DESCRIPTOR.enum_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RaftRequest = _reflection.GeneratedProtocolMessageType('RaftRequest', (_message.Message,), {
  'DESCRIPTOR' : _RAFTREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.RaftRequest)
  })
_sym_db.RegisterMessage(RaftRequest)

KVRequest = _reflection.GeneratedProtocolMessageType('KVRequest', (_message.Message,), {
  'DESCRIPTOR' : _KVREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.KVRequest)
  })
_sym_db.RegisterMessage(KVRequest)

RaftResponse = _reflection.GeneratedProtocolMessageType('RaftResponse', (_message.Message,), {

  'Redirect' : _reflection.GeneratedProtocolMessageType('Redirect', (_message.Message,), {
    'DESCRIPTOR' : _RAFTRESPONSE_REDIRECT,
    '__module__' : 'kv_pb2'
    # @@protoc_insertion_point(class_scope:kv.RaftResponse.Redirect)
    })
  ,

  'Result' : _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR' : _RAFTRESPONSE_RESULT,
    '__module__' : 'kv_pb2'
    # @@protoc_insertion_point(class_scope:kv.RaftResponse.Result)
    })
  ,
  'DESCRIPTOR' : _RAFTRESPONSE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.RaftResponse)
  })
_sym_db.RegisterMessage(RaftResponse)
_sym_db.RegisterMessage(RaftResponse.Redirect)
_sym_db.RegisterMessage(RaftResponse.Result)


# @@protoc_insertion_point(module_scope)
